name: hello-world
on: push
jobs:
  my-job:
    runs-on: conjur
    steps:
      - name: my-step
        run: echo "Hello World!"
  test-conjur:
    runs-on: conjur
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.2
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: acme
          host_id: ${{ secrets.CONJUR_USERNAME }}
          api_key: ${{ secrets.CONJUR_API_KEY }}
          secrets: db-login;db-password
      - name: print secrets
        run: echo "$db-password"
